#!/bin/bash
# Claude Code Authentication Helper for Headless Docker Containers
# This script helps you authenticate Claude Code when running in a Docker container

echo "=========================================="
echo "Claude Code Authentication Helper"
echo "=========================================="
echo ""
echo "Since the container is headless, follow these steps:"
echo ""
echo "STEP 1: Start Claude Code"
echo "  Run: claude"
echo ""
echo "STEP 2: Copy the OAuth URL"
echo "  Look for a line that says: 'Browser didn't open? Use the url below'"
echo "  Copy the ENTIRE URL that follows (it's very long)"
echo ""
echo "STEP 3: Open URL in Browser (on your HOST machine)"
echo "  - Open a web browser on your computer (NOT in the container)"
echo "  - Paste the OAuth URL you copied"
echo "  - Sign in with your Anthropic/Claude account"
echo "  - Authorize Claude Code"
echo ""
echo "STEP 4: Get Authorization Code"
echo "  After authorizing, you'll see an authorization code"
echo "  OR the code will be in the redirect URL"
echo "  Copy this code (usually 6-8 characters)"
echo ""
echo "STEP 5: Paste Code Back"
echo "  - Return to this terminal"
echo "  - Paste the code at the prompt: 'Paste code here if prompted >'"
echo "  - Press Enter"
echo ""
echo "=========================================="
echo "Alternative: Using API Key"
echo "=========================================="
echo ""
echo "If you have an Anthropic API key, you can set it as an environment variable:"
echo ""
echo "  export ANTHROPIC_API_KEY=your_api_key_here"
echo "  claude"
echo ""
echo "To make it persistent, add to docker-compose.yml environment section"
echo ""
echo "=========================================="
